### ISSUE TITLE
graphviz == 2999 not found

### ISSUE THREAD

**Issue by abertschi** [BurntSushi/erd#11]
Hi there,

I have a problem installing erd on my system.

Using `cabal install erd`, I get

```
cabal: Could not resolve dependencies:
trying: erd-0.1.3.0 (user goal)
next goal: base (dependency of erd-0.1.3.0)
rejecting: base-4.8.0.0/installed-901... (conflict: erd => base==4.7.*)
rejecting: base-4.8.0.0, 4.7.0.2, 4.7.0.1, 4.7.0.0, 4.6.0.1, 4.6.0.0, 4.5.1.0,
4.5.0.0, 4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2, 4.2.0.1, 4.2.0.0,
4.1.0.0, 4.0.0.0, 3.0.3.2, 3.0.3.1 (global constraint requires installed
instance)
Dependency tree exhaustively searched.
```

Trying to download the source and firing up `cabal configure`, graphiz does not seem to be found.

```
Configuring erd-0.1.3.0...
cabal: At least the following dependencies are missing:
graphviz ==2999.*
```

`cabal update` was previously run.

Any held would be appreciated.

**Comment by eric-brechemier** [comment]
@abertschi I feel like [this commit](https://github.com/eric-brechemier/erd/commit/51b0807564f5be7cda06bec8bb54bbe3839f6c38) might fix your issue. Perhaps you can try to install erd from latest source?

@BurntSushi What do you think? Would it help to update the version published on cabal?

**Comment by eric-brechemier** [comment]
@abertschi I tried a fresh install from OS X 10.10.3 today,, and I had no issue.

I followed these steps:

1. Install GHC for OSX from: https://www.haskell.org/downloads/osx
2. launch GHC for OSX and follow step by step instructions to configure ghc
3. from a terminal, run `cabal update` to initialize the list of packages for cabal
4. install erd by running `cabal erd`

**Comment by abertschi** [comment]
@eric-brechemier, I cloned your fork from [this commit](https://github.com/eric-brechemier/erd/commit/51b0807564f5be7cda06bec8bb54bbe3839f6c38), performed a `cabal update `and `cabal install erd` with `brew install graphviz` beforehand and managed to solve the issue. Thanks a lot.

**Comment by eric-brechemier** [comment]
@abertschi I'm glad it helped. For your information, this commit has been merged upstream, so you should be good to go with the master branch of the main project (BurntSushi/erd) as well.
