### ISSUE TITLE
 primary keys are not underlined and foreign keys are not italicized.

### ISSUE THREAD

**Issue by oz123** [BurntSushi/erd#15]
The readme states:

> Note that primary keys are underlined while foreign keys are italicized.

I installed erd from cabal, and I invoked erd with the given example and the output file I get is not as described:
![simple](https://cloud.githubusercontent.com/assets/1083045/9742388/23729956-5660-11e5-8b72-ae39b7774832.png)

I would appreciate if you looked into it.

**Comment by varontron** [comment]
Same issue building from source.

**Comment by 0culus** [comment]
This is a problem for me too. @BurntSushi  any ideas?

**Comment by bbqsrc** [comment]
It's probably a bug in graphviz itself:

http://www.graphviz.org/mantisbt/view.php?id=2592#c1041

**Comment by xavriley** [comment]
I can confirm that the following fixed this for me running on OSX

```
brew uninstall graphviz
brew install cairo pango graphviz --with-pangocairo
```
