### ISSUE TITLE
Another ER scripting language

### ISSUE THREAD

**Issue by JohnWCartmell** [BurntSushi/erd#28]
Having read the readme can I add that I have been developing an ER scripting language for some time at Cyprotex Discovery Ltd and am now releasing on GitHub https://github.com/JohnWCartmell/ERmodelSeries1/blob/master/README.md.  Sadly no automatic diagram layout. Work is in progress to improve the diagram support.

**Comment by BurntSushi** [comment]
There's nothing in the README that tells me how to use the code, so I'm not really comfortable linking to it. Please provide a simple hello world example like the one in erd's README: https://github.com/BurntSushi/erd#quick-example

**Comment by JohnWCartmell** [comment]
That's fine. Don't worry about it. Just wanted to communicate the existence
to you. Best. John

**Comment by BurntSushi** [comment]
All righty, thanks!
