### ISSUE TITLE
Consider adding QuickDBD to "Similar Software"

### ISSUE THREAD

**Issue by bbkane** [BurntSushi/erd#35]
https://app.quickdatabasediagrams.com/#/ is a free web-based app that uses a text format to draw diagrams. I've used it with some success for simple database diagrams. You might add it to the Similar Software section of the README.

**Comment by nickolay** [comment]
While googling the graphviz syntax for ER diagrams, I came across http://schemaspy.sourceforge.net/sample/relationships.html (Java, open-source, automatic documentation from the DB). Not similar, but related.
