### ISSUE TITLE
watching an input file

### ISSUE THREAD

**Issue by windbender** [BurntSushi/erd#37]
It would be nice to have erd be able to watch an input file for changes and then mirror the changes into the transformed file.

**Comment by sandebert** [comment]
It sure would, and that's why we have tools like [entr](http://entrproject.org/), [watchexec](https://github.com/watchexec/watchexec) and [several other alternatives](https://news.ycombinator.com/item?id=13856623).

I propose to close this ticket. :)

**Comment by windbender** [comment]
It would. I'm currently using fswatch.  However, now I need a script and additional install to pull all that together.  I certainly do not view this as a must have,  but something more of a "nice to have".

**Comment by BurntSushi** [comment]
This program is effectively unmaintained. It hasn't seen any real work in years. There's no way a major feature like this will ever happen.
