### ISSUE TITLE
Request for release

### ISSUE THREAD

**Issue by sandebert** [BurntSushi/erd#38]
Looking at the instructions it doesn't seem overly complicated to compile erd for Linux, but I kind of feel a resistance to installing Haskell just for this (never needed it before) and at least getting a shallow insight into that universe.

As such I was wondering if it might be possible to perhaps just make a release for Linux, containing nothing more than the erd binary? (I'm making the assumption that erd is a single file.)

Please? :)

**Comment by BurntSushi** [comment]
No, sorry.
