### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by mcdejonge** [BurntSushi/erd#39]
Hi,

Cool tool!

I did have some issues installing on OS X + Homebrew, though:

* cabal install erd does not work at all
* Installing manually fails as well:
    * base is set to be larger than 4.5, but the current version is 4.11 which for some reason is not seen as being larger than 4.5 (probably a cabal issue?). Workaround: set base >= 4.1
    * graphviz is not installed automatically, so you need to manually do cabal install graphviz

Once you've done this, however, building and running erd works fine.

I suspect both of these are cabal issues and not so much erd issues, but it might be nice to mention them in the installation instructions.

**Comment by mrgou** [comment]
Hi,

I'm trying to run erd, but have no knowledge whatsoever about Haskell and cabal. For your workaround on the first issue, how do you set base >= 4.1 ?

Thanks!

**Comment by mcdejonge** [comment]
You can do this in the cabal file in the source directory (erd.cabal)

**Comment by mmzx** [comment]
Please let us know whether installation with cabal succeeds as mentioned in #27 .
The command would be `cabal install --allow-newer erd`.

**Comment by zhujinxuan** [comment]
Hi, I think it is due to, when @BurntSushi publishing the package last time, the cabal file is `base == 4.7.*` (http://hackage.haskell.org/package/erd-0.1.3.0/src/erd.cabal)

I do not have the permission to republish it.  Perhaps @BurntSushi can republish with current cabal?

As a temporary solution, `cabal install --allow-newer erd`.

**Comment by mmzx** [comment]
In order to publish _erd_ on hackage the version has to be increased ( #52 ). Once the PRs are all reviewed would be nice to do this.

**Comment by mmzx** [comment]
However, the request in this ticket: increasing version of _base_, has already been done.
