### ISSUE TITLE
Fails to install on Arch Linux

### ISSUE THREAD

**Issue by andrea-berling** [BurntSushi/erd#41]
It fails to install on Arch Linux. I believe I have installed all the needed dependencies (graphviz, ghc, cabal-install,...) but it still has errors and it won't install. This is the output of the `cabal configure` command:
```
Warning: The configure command is a part of the legacy v1 style of cabal
usage.
Please switch to using either the new project style and the new-configure
command or the legacy v1-configure alias as new-style projects will become the
default in the next version of cabal-install. Please file a bug if you cannot
replicate a working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

Resolving dependencies...
Warning: solver failed to find a solution:
Could not resolve dependencies:
[__0] trying: erd-0.1.3.0 (user goal)
[__1] trying: text-1.2.3.1/installed-1.2... (dependency of erd)
[__2] next goal: binary (dependency of text)
[__2] rejecting: binary-0.8.6.0/installed-0.8... (conflict: erd =>
containers==0.5.*, binary => containers==0.6.0.1/installed-0.6...)
[__2] fail (backjumping, conflict set: binary, erd, text)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: erd, binary, text
Trying configure anyway.
Configuring erd-0.1.3.0...
cabal: Encountered missing dependencies:
containers ==0.5.*
```

**Comment by BurntSushi** [comment]
I don't actively maintain this project. There are plenty of issues documenting installation options. Apparently, over the years, cabal has broken the build for this project. I don't have any plans to fix it.

**Comment by andrea-berling** [comment]
I see. It's a shame though, your software looked exactly like what I needed and, as you said, there are pretty much no alternatives to it that do the same (and erwiz site is down too, so tough titties for me I guess).

**Comment by BurntSushi** [comment]
You might consider looking into how to fix it.

**Comment by BurntSushi** [comment]
Sure. Public issues are preferable. I don't know how much use I'll be though. I haven't looked at this project in years.

**Comment by mmzx** [comment]
@andrea-berling You may have a look at the updated repository (branch: master), you should be able to build to project now either with stack or cabal (`cabal install --allow-newer erd`).

**Comment by andrea-berling** [comment]
@mmzx I managed to install it successfully, thanks a lot.
