### ISSUE TITLE
Improve warning when graphviz is missing

### ISSUE THREAD

**Issue by peplin** [BurntSushi/erd#5]
First off, awesome tool - thanks!

I had one hiccup getting started - I ran `cabal install erd` and saw something about graphviz in the output, so I incorrectly assumed that dependency was taken care of automatically. When I tried to use erd I would get the confusing error:

```
erd: dot: runInteractiveProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

which after a few minutes I realized meant that `dot` was not found, meaning graphviz. After installing that everything is fine, of course.

I realize it's mentioned as a requirement in the README, but a warning if `dot` isn't found along the lines of `Looks like Graphviz isn't installed, can't find the 'dot' program` would probably be helpful for new users.

**Comment by corny** [comment]
Fully agree :+1:

**Comment by iwanluijks** [comment]
On Windows, when Graphviz is installed, it might not always be the case its installation directory is added to the PATH environment variable. It might be a good one, at least extra informative, to add the following to the warning you suggest: "Make sure the Graphviz bin-directory added to your PATH environment variable."

**Comment by mmzx** [comment]
It has been added in #45 .
