### ISSUE TITLE
Releasing a new version

### ISSUE THREAD

**Issue by mmzx** [BurntSushi/erd#52]
There are some reasons that would favor creating a new version:
- Issue #14 has been actually done in commit: 51b0807564f5be7cda06bec8bb54bbe3839f6c38 .
- It would be nice to have a new version uploaded to hackage and that requires at least a minor version bump.
- There has been new features added.
- The new build system of hackage would be utilized, currently (#14) does not let the build to succeed.

What would you think about the new version to be 0.1.3.1 to make a minor version bump?

**Comment by mmzx** [comment]
@BurntSushi, currently you are the maintainer of this package according to the hackage database. If this issue was relevant could you please change the settings to make it possible to upload a new version to hackage?

**Comment by BurntSushi** [comment]
@mmzx I can change the settings sure. But I need to enter a user account for uploading new versions. What is your Hackage account username?

**Comment by mmzx** [comment]
@BurntSushi it is: mmzx .

**Comment by BurntSushi** [comment]
@mmzx Thanks. I've added you.

**Comment by mmzx** [comment]
Brilliant, thank you! Later today I will make the necessary action(s).
What do you think about v1.4.0?

**Comment by BurntSushi** [comment]
If there's a breaking change, then do a major version bump.

**Comment by mmzx** [comment]
Thanks! 0.2.0.0 has been uploaded to hackage.
