### ISSUE TITLE
Unable to render `examples/simple.er`

### ISSUE THREAD

**Issue by georgexsh** [BurntSushi/erd#55]
using erd via docker, image is rebuild from https://github.com/vranac/erd
```
docker run --rm -v "$(pwd)":/erd erd -f png -i simple.er
``` 
error message:
```
"simple.er" (line 8, column 1):
unexpected '`'
expecting end of input, entity declaration, relationship, attribute, comment or whitespace
```

**Comment by mmzx** [comment]
@georgexsh , The package version that is available on hackage is fairly old (would rather say: obsolete), I am trying to get a new version uploaded, at some point, it must happen... (#52).

I recommend you update your docker file [1], to use the master branch of this repository and get either cabal or stack (both works equally well) to build it for you for the time being.

You can also use cabal to get the source for you by `cabal get erd --source-repository=head`. Please note that this does not build or install for you, only fetches the code from github.
Probably you want to do it like:
`cabal get erd --source-repository=head && cd ./erd && cabal install --allow-newer` .

Additionally I recommend using the **-o** argument to avoid dumping png file to stdout.

[1] https://github.com/vranac/erd/blob/8d99e8f7ff7fb1af1ca9d1035a96caeef5e31399/Dockerfile#L11

**Comment by mmzx** [comment]
@georgexsh from now, you shall not need to make the above workaround, cabal as the source of the package should work in your use-case as expected.
