### ISSUE TITLE
Adjusting the output width

### ISSUE THREAD

**Issue by corny** [BurntSushi/erd#6]
My generated diagram is too wide. How can I adjust the width of the output?

**Comment by BurntSushi** [comment]
You can't, at least not with `erd` directly. See: https://github.com/BurntSushi/erd#philosophy

Your best bet is to use `erd` to output a `dot` file, and the fiddle with GraphViz options. But it's probably a deep rabbit hole.

**Comment by corny** [comment]
Ok, thanks. I will solve my problem by using `dot` as output.
