### ISSUE TITLE
Add support of regular dot tables as output,  apart from html.

### ISSUE THREAD

**Issue by bollafa** [BurntSushi/erd#72]
As the [README](https://github.com/BurntSushi/erd/blob/master/README.md) itself promotes:

> (I would not be against a small addition to erd that uses no formatting and writes entities as regular dot tables.)

There's a very rough support of it [here](https://github.com/bollafa/erd/commit/7ec9fa65b22b23d10d69e25a57bc4fff7fabed10)

It's still quite ad-hoc, and I created this issue to discuss the implementation details, such as 
the new option name and how to refactor the function that maps an ER diagram to a GraphViz one.

I have added the option `--no-html` to choose between the two modes ( and while I was testing if I had added it correctly i found #71 )

**Comment by mmzx** [comment]
Hi @bollafa, 
Thank you, I have compiled and used your [solution](https://github.com/bollafa/erd/commit/7ec9fa65b22b23d10d69e25a57bc4fff7fabed10).

It is operational, so would you mind making the usual ceremony of creating a pull-request from your branch _vanilla-dot_, so perhaps the details of the code could be further specified in the PR?

I am not sure whether the _--no-html_ flag is good as a name. The behavior only changes the resulted formatting of the **entities** (tables) in the diagram. So, what would you think about something like _dot-entity_ or similarly specific for the argument flag?

In the PR we could easily work on the code...

**Comment by bollafa** [comment]
I have created the ceremonial PR :) .

I don't mind at all changing the flag name. I think _--no-html_ can be quite misleading to someone that does not know the implementation details of Erd. _dot-entity_ seems okay to me. Just another _- perhaps unnecessary -_ idea:  what do you think about _dot-table_?

**Comment by mmzx** [comment]
> I don't mind at all changing the flag name. I think _--no-html_ can be quite misleading to someone that does not know the implementation details of Erd. _dot-entity_ seems okay to me. Just another _- perhaps unnecessary -_ idea: what do you think about _dot-table_?

I'm not against _dot-table_, although still think saying entity is more descriptive. Please choose the one you think is better.

**Comment by mmzx** [comment]
(PR #74) resolves this issue.
