### ISSUE TITLE
Make edges style (dashed/solid) customizable

### ISSUE THREAD

**Issue by kukimik** [BurntSushi/erd#93]
The edges in the graph are dashed and this is hardcoded in this line: https://github.com/BurntSushi/erd/blob/06c72643682a42a890a2ffadac82cfc1dafd5edd/app/Main.hs#L54

Can we make this customizable? I am aware of the _Philosophy_ statement:

> I don't intend for erd to have a large feature set with a lot of options for customizing the appearance of ER diagrams. 

However, this dashed style may be confusing, because in some ERD notations (e.g. [Baker's notation](https://vertabelo.com/blog/barkers-erd-notation/) dashed lines have a meaning. In some usecases, like mine, this is a problem.

If this idea gets accepted, I'll be happy to make a PR.

**Comment by mmzx** [comment]
Sure, go ahead. You may look up the related graphviz documentation for the supported types of edges.
